[package]
name = "postgres_viewer"
version = "0.1.0"
edition = "2021"

[dependencies]
postgres = { version = "0.19.4", features = ["with-chrono-0_4", "with-serde_json-1"] }
chrono = "0.4"
serde_json = "1.0"